---
apiVersion: v1
kind: Service
metadata:
  name: product-api
  namespace: default
  labels:
    app: product-api
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: product-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: product-api
  namespace: default
automountServiceAccountToken: true
---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: product-api
  namespace: default
spec:
  protocol: "http"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-api
  namespace: default
  labels:
    app: product-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-api
  template:
    metadata:
      labels:
        app: product-api
      annotations:
        consul.hashicorp.com/connect-inject: "true"
    spec:
      serviceAccountName: product-api
      containers:
        - name: product-api
          image: 346424633902.dkr.ecr.eu-west-1.amazonaws.com/backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: DB_URI
              value: "host=product-api-db port=5432 user=postgres password=password dbname=products sslmode=disable"
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 30

