on:
  pull_request:
    branches:
      - main

env:
  AWS_REGION: eu-west-1

permissions:
  id-token: write
  contents: read

jobs:
  tf-plan-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ORG_ID }}:role/github-role
          role-session-name: github-session
          aws-region: ${{ env.AWS_REGION }}
      - uses: hashicorp/setup-terraform@v3
      - name: Terraform init
        run: terraform init
      - name: Terraform plan
        run: |
          terraform plan
  tf-plan-helm:
    runs-on: ubuntu-latest
    needs: [tf-plan-infrastructure]
    defaults:
      run:
        working-directory: ./helm
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ORG_ID }}:role/github-role
          role-session-name: github-session
          aws-region: ${{ env.AWS_REGION }}
      - uses: hashicorp/setup-terraform@v3
      - name: Terraform init
        run: terraform init
      - name: Terraform apply
        run: |
          terraform apply -auto-approve -input=false
  lint:
    name: lint
    needs: [tf-plan-helm]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up npm and node
        uses: actions/setup-node@v4
        with:
          cache: 'npm'
      - name: Lint
        run: |
          cd frontend
          npm ci
          npm run lint
