on:
  pull_request:
    branches:
      - main

env:
  AWS_REGION: eu-west-1

permissions:
  id-token: write
  contents: read

jobs:
  tf-plan:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./aws
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ORG_ID }}:role/github-role
          role-session-name: github-session
          aws-region: ${{ env.AWS_REGION }}
      - uses: hashicorp/setup-terraform@v3
      - name: Terraform init
        run: terraform init
      - name: Terraform plan
        run: |
          terraform plan
